spring:
  application:
    name: projeto
  datasource:
    url: jdbc:mysql://localhost/sgp2
    username: root
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate